# Generated by Django 4.2.1 on 2023-05-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic_comment_post_topic'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='forum_post_publish_f16607_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
