# Generated by Django 4.2.1 on 2023-06-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_topic_slug_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
