version: '3.4'

services:
  web:
    image: choko2/dev_forum
    command: gunicorn dev_forum.wsgi:application --bind 0.0.0.0:8000
    build: .
    volumes:
      - ./static_files:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - envs/.env
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static_files:/home/app/web/staticfiles
      - ./media:/home/app/web/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    links:
      - web
