# Generated by Django 4.2.1 on 2023-07-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appuser_remember_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='remember_me',
        ),
    ]
