# Generated by Django 4.2.1 on 2023-07-22 01:59

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_appuser_remember_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile-pictures', validators=[apps.core.validators.validate_file_size]),
        ),
    ]
