# Generated by Django 4.2.1 on 2023-07-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['pk'], 'verbose_name': 'MyCustomUser'},
        ),
    ]
