# Generated by Django 4.2.1 on 2023-05-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile-pictures'),
        ),
    ]
