version: '3.4'

services:
  web:
    image: choko2/dev_forum
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./envs/.env
    volumes:
      - ./postgresql:/var/lib/postgresql/data
